version: "3.9"

services:
  db:
    image: postgres:15
    container_name: crypto_postgres15
    restart: no
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crypto-db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine  # or redis:7.2, redis:7-alpine, redis:latest
    container_name: crypto_redis
    restart: no
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  app:
    build: .
    container_name: crypto-fastapi
    
    restart: no
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
      - ./templates:/app/templates
      - ./.env.example:/app/.env.example
    depends_on:
      - db
      - redis
    command: >
      sh -c "cp -n .env.example .env || true &&
      dockerize -wait tcp://db:5432 -wait tcp://redis:6379 -timeout 60s &&
      alembic upgrade head &&
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --reload-dir /app/app"
volumes:
  postgres_data:
  redis_data:
